### ISSUE TITLE
Is this project still in progress?

### ISSUE THREAD

**Issue by 0xCUB3** [vinaypundith/bettercamp#1]
This is very interesting - installing windows on older Macs! What exactly is the goal of this project? Are you still working on it?

**Comment by vinaypundith** [comment]
The goal of the project is to automate the driver tweaks needed to get newer Windows versions (10/11) working on older Mac computers (as Apples Boot Camp tool by default uses old drivers that cause issues on new hardware). Yes I'm still working on it,  but haven't been able to put much time into it - I'm a busy university student and writing this tool needs me to make several burner Windows installations to test code on.  Any help you can offer with coding would be much appreciated!  This started as a team project but I am the only one left :-(
